name: publish
on:
  workflow_dispatch:
  push:
    branches:
      - 'release-0.521'
    tags:
      - 'v*'
      - '!pkg*'

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish container images
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Import environment variables from file
        run: cat ".github/env" >> $GITHUB_ENV
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '${{ env.golang-version }}'
      - name: login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: registry.hub.docker.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build images and push
        run: |
          export REGISTRIES="registry.hub.docker.com"
          export IMAGE_OPERATOR="mikejianzhang/prometheus-operator"
          export IMAGE_RELOADER="mikejianzhang/prometheus-config-reloader"
          ./scripts/push-docker-image.sh
